project_id = "pbxormchfloeaqrkhbvz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

# Email template directory
[auth.email.template]
[auth.email.smtp]

[edge_runtime]
ip_version = "dual"

[functions.video-sfu]
verify_jwt = false